title: Michael Jung
author:
  name: Michael Jung
  email: m (dot) jung (at) vu.nl
description: > # this means to ignore newlines until "show_excerpts:"
  This is my personal homepage where I give insights into my ongoing work and ambitions.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin:  'classic'
  skin_dark: 'dark'

  # generate social links in footer
  social_links:
    github:  mjungmath
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: seminar
markdown: kramdown
kramdown:
   math_engine: mathjax

# include folders
include: ['_pages']

# seminar collection
collections:
  events:
    output: true
    permalink: /phdseminar/:year/:month/:day/:name
    sort_by: dt_start

# set timezone
timezone: Europe/Amsterdam

plugins:
 - jekyll-feed
 - jekyll-seo-tag
